import { ClipboardList, ShieldCheck, MessageCircle } from "lucide-react"
import { rtpTable, statusMeta, clinicalRiskFlags, rtpCriteria } from "../data/players"
import RecommendationsPanel from "../components/RecommendationsPanel"
import Abbr from "../components/Abbr"
import { linkifyAbbreviations } from "../utils/linkifyAbbreviations"
import { useMessages } from "../context/MessagesContext"

export default function MedicalView() {
  const { messages } = useMessages()

  return (
    <div className="space-y-6">
      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
        <h3 className="text-sm font-semibold text-gray-900">Return-to-Play Status</h3>
        <div className="mt-3 overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-gray-200 text-xs uppercase tracking-wide text-gray-400">
                <th className="py-2 pr-4 font-medium">Player</th>
                <th className="py-2 pr-4 font-medium">Injury Type</th>
                <th className="py-2 pr-4 font-medium">Days Since Injury</th>
                <th className="py-2 pr-4 font-medium"><Abbr term="RTP">RTP</Abbr> Criteria Met</th>
                <th className="py-2 pr-4 font-medium">Clearance Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {rtpTable.map((row) => {
                const meta = statusMeta[row.status]
                return (
                  <tr key={row.playerId}>
                    <td className="py-3 pr-4 font-medium text-gray-900">{row.name}</td>
                    <td className="py-3 pr-4 text-gray-600">{row.injury}</td>
                    <td className="py-3 pr-4 font-mono text-gray-600">
                      {row.days} {row.daysNote}
                    </td>
                    <td className="py-3 pr-4 text-gray-600">{row.criteriaMet}</td>
                    <td className="py-3 pr-4">
                      <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${meta.bg} ${meta.text}`}>
                        {row.status}
                      </span>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
          <div className="flex items-center gap-2">
            <ClipboardList className="h-4 w-4 text-gray-500" />
            <h3 className="text-sm font-semibold text-gray-900">
              <Abbr term="ML">ML</Abbr> Predicted Injury Probability (next 7 days)
            </h3>
          </div>
          <div className="mt-4 space-y-4">
            {clinicalRiskFlags.map((flag) => {
              const barColor = flag.level === "high" ? "bg-red-600" : "bg-amber-600"
              return (
                <div key={flag.playerId}>
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-medium text-gray-900">{flag.name}</span>
                    <span className="font-mono font-semibold text-gray-700">{flag.probability}%</span>
                  </div>
                  <div className="mt-1.5 h-2 w-full rounded-full bg-gray-100">
                    <div className={`h-2 rounded-full ${barColor}`} style={{ width: `${flag.probability}%` }} />
                  </div>
                </div>
              )
            })}
          </div>
          <p className="mt-4 text-xs text-gray-400">
            Predictions generated by Logistic Regression model (recall: 57.4%, precision: 14.6%)
          </p>
        </div>

        <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
          <div className="flex items-center gap-2">
            <ShieldCheck className="h-4 w-4 text-gray-500" />
            <h3 className="text-sm font-semibold text-gray-900">
              Evidence-Based <Abbr term="RTP">RTP</Abbr> Criteria
            </h3>
          </div>
          <ul className="mt-4 space-y-2.5">
            {rtpCriteria.map((item) => (
              <li key={item} className="flex gap-2 text-sm text-gray-600">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-green-600" />
                {linkifyAbbreviations(item)}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <RecommendationsPanel
        role="medical"
        title="Clinical Recommendations"
        emptyText="No clinical recommendations logged yet — add one below."
        addLabel="Add clinical note"
        borderClass="border-l-red-600"
      />

      <div className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
        <div className="flex items-center gap-2">
          <MessageCircle className="h-4 w-4 text-gray-500" />
          <h3 className="text-sm font-semibold text-gray-900">Player Messages</h3>
        </div>
        {messages.length === 0 ? (
          <p className="mt-2 text-sm italic text-gray-400">No messages from players yet.</p>
        ) : (
          <div className="mt-2 divide-y divide-gray-100">
            {[...messages].reverse().map((m) => (
              <div key={m.id} className="py-3 first:pt-0 last:pb-0">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-gray-900">{m.from}</span>
                  <span className="text-xs text-gray-400">{new Date(m.createdAt).toLocaleString()}</span>
                </div>
                <p className="mt-1 text-sm text-gray-600">{linkifyAbbreviations(m.text)}</p>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
